name: Terraform Dev

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  terraform-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: live/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  checkov-test:
    needs: terraform-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: live/dev
          framework: terraform

  terraform-plan:
    needs: checkov-test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: live/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::841338716314:role/github-actions-terraform-role
          aws-region: us-east-2

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan


